name: deploy to gitlab

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn install
          yarn run docs:build

      - name: Configure Private Key
        env:
            # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
            SSH_PUB_KEY: ${{secrets.GITEE_RSA_PUB_KEY}}
        run: |
            mkdir -p ~/.ssh
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            echo "$SSH_PUB_KEY" > ~/.ssh/id_rsa.pub
            chmod 600 ~/.ssh/id_rsa
            echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Push to Gitlab
        env:
          PROJ_PATH: ${{github.workspace}}
          GIT_LAB: git@gitlab.com:wsj0051/wsj0051.gitlab.io.git
        run: |
          cd ${PROJ_PATH}/docs/.vuepress/dist
          mkdir -p ~/wsj0051
          rm -rf .github/ .git/
          git clone ${GIT_LAB} ~/wsj0051/vue-docs
          rm -rf  ~/wsj0051/vue-docs/public/*
          cp -r ./*  ~/wsj0051/vue-docs/public
          cd ~/wsj0051/vue-docs
          git config --global user.email "wsj0051@163.com"
          git config --global user.name "wsj0051"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet origin master         